# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SMlDLPmr42R75_sB9E-tP8LMl-JnfzT
"""

# %% [markdown]
# # Task 1: LSTM Autoencoder for Single‑Genre Music Generation (MAESTRO) – FIXED for Audible MIDI
#
# This notebook implements an unsupervised LSTM Autoencoder that learns to reconstruct
# short piano‑roll windows (8 seconds) from the MAESTRO dataset. After training, new
# music is generated by sampling latent vectors from N(0, I).
#
# **Fixes for silent outputs:**
# - Higher α=0.95 in Focal Loss (strong push for note cells)
# - Generation threshold = 0.05 + probability scaling (×2.0)
# - Minimum note duration = 0.001 seconds

# %% [code]
# Installing required package/libraries
!pip install pretty_midi -q

# %% [code]
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
import pretty_midi
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import random
from collections import Counter

# For reproducibility
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# %% [markdown]
# ## 1. Configuration

# %% [code]
# Dataset paths (Kaggle input)
DATA_ROOT = "/kaggle/input/datasets/ummamariumalam/maestro-v2/maestro-v2.0.0"
CSV_PATH = os.path.join(DATA_ROOT, "maestro-v2.0.0.csv")

# Preprocessing parameters
FS = 16                     # frames per second
WINDOW_SEC = 8              # 8 seconds per window
WINDOW_LEN = FS * WINDOW_SEC   # 128 frames
MIN_ACTIVE_RATIO = 0.02    # discard windows with <2% active cells
PITCH_START = 21           # MIDI note 21 = A0
PITCH_END = 108            # MIDI note 108 = C8
NUM_PITCHES = PITCH_END - PITCH_START + 1   # 88

# Training parameters
BATCH_SIZE = 64
EPOCHS = 50
LR = 1e-3
LATENT_DIM = 64
HIDDEN_DIM = 256
NUM_LAYERS = 2

# Generation parameters (FIXED: lower threshold and scaling)
NUM_GEN_SAMPLES = 5
GEN_THRESHOLD = 0.05        # much lower than default 0.5
PROB_SCALE = 2.0            # boost probabilities to make notes appear
MIN_NOTE_DURATION = 0.001   # seconds (was 0.02, now very short notes allowed)

# Output directories
os.makedirs("generated_midi", exist_ok=True)
os.makedirs("plots", exist_ok=True)

# %% [markdown]
# ## 2. Exploratory Data Analysis (EDA)

# %% [code]
def explore_dataset(csv_path):
    df = pd.read_csv(csv_path)
    print(f"Total recordings: {len(df)}")
    print(f"Train/val/test split counts:\n{df['split'].value_counts()}")

    # Duration histogram
    plt.figure(figsize=(8,4))
    plt.hist(df['duration'], bins=50, color='steelblue', edgecolor='black')
    plt.xlabel('Duration (seconds)')
    plt.ylabel('Number of pieces')
    plt.title('MAESTRO Piece Duration Distribution')
    plt.savefig("plots/duration_histogram.png", dpi=150)
    plt.show()

    # Pitch distribution
    pitch_counter = Counter()
    sample_files = df.sample(min(20, len(df)))['midi_filename'].values
    for rel_path in sample_files:
        full_path = os.path.join(DATA_ROOT, rel_path)
        try:
            midi = pretty_midi.PrettyMIDI(full_path)
            for inst in midi.instruments:
                for note in inst.notes:
                    if PITCH_START <= note.pitch <= PITCH_END:
                        pitch_counter[note.pitch] += 1
        except:
            continue

    if pitch_counter:
        pitches = sorted(pitch_counter.keys())
        counts = [pitch_counter[p] for p in pitches]
        plt.figure(figsize=(10,4))
        plt.bar(pitches, counts, width=0.8, color='coral')
        plt.xlabel('MIDI Pitch')
        plt.ylabel('Note count')
        plt.title('Pitch Distribution (sample of pieces)')
        plt.savefig("plots/pitch_distribution.png", dpi=150)
        plt.show()

explore_dataset(CSV_PATH)

# %% [markdown]
# ## 3. Preprocessing: MIDI → Piano‑Roll Windows

# %% [code]
def midi_to_pianoroll_windows(midi_path, fs=FS, window_len=WINDOW_LEN,
                              min_active_ratio=MIN_ACTIVE_RATIO):
    """Return list of windows (each shape (window_len, NUM_PITCHES))."""
    try:
        midi = pretty_midi.PrettyMIDI(midi_path)
        piano_roll = midi.get_piano_roll(fs=fs)[PITCH_START:PITCH_END+1, :]  # (88, T)
        piano_roll = piano_roll.T   # (T, 88)
        piano_roll = (piano_roll > 0).astype(np.float32)

        T_total = piano_roll.shape[0]
        windows = []
        for start in range(0, T_total - window_len + 1, window_len):
            win = piano_roll[start:start+window_len, :]
            if np.mean(win) >= min_active_ratio:
                windows.append(win)
        return windows
    except Exception as e:
        print(f"Error processing {midi_path}: {e}")
        return []

def preprocess_split(df_split, split_name):
    """Process all MIDI files in a given split and save windows."""
    out_file = f"pianoroll_{split_name}.npy"
    if os.path.exists(out_file):
        print(f"Loading existing {out_file}")
        return np.load(out_file)

    all_windows = []
    for _, row in tqdm(df_split.iterrows(), total=len(df_split), desc=f"Processing {split_name}"):
        midi_rel_path = row['midi_filename']
        midi_full_path = os.path.join(DATA_ROOT, midi_rel_path)
        windows = midi_to_pianoroll_windows(midi_full_path)
        all_windows.extend(windows)

    if not all_windows:
        raise RuntimeError(f"No windows generated for split {split_name}")

    data = np.stack(all_windows, axis=0)
    np.save(out_file, data)
    print(f"Saved {split_name} split: {data.shape}")
    return data

# Read splits from CSV
df_all = pd.read_csv(CSV_PATH)
train_df = df_all[df_all['split'] == 'train']
val_df   = df_all[df_all['split'] == 'validation']
test_df  = df_all[df_all['split'] == 'test']

train_data = preprocess_split(train_df, 'train')
val_data   = preprocess_split(val_df, 'validation')
test_data  = preprocess_split(test_df, 'test')

print(f"Train windows: {train_data.shape}, Val windows: {val_data.shape}, Test windows: {test_data.shape}")

# %% [markdown]
# ## 4. PyTorch Dataset & DataLoader

# %% [code]
class PianoRollDataset(Dataset):
    def __init__(self, data):
        self.data = torch.from_numpy(data).float()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

train_dataset = PianoRollDataset(train_data)
val_dataset   = PianoRollDataset(val_data)
test_dataset  = PianoRollDataset(test_data)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

# %% [markdown]
# ## 5. LSTM Autoencoder Model with Focal Loss (α=0.95, γ=0)

# %% [code]
class Encoder(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, num_layers):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, dropout=0.3 if num_layers > 1 else 0)
        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(hidden_dim, latent_dim)

    def forward(self, x):
        _, (h_n, _) = self.lstm(x)
        h_last = h_n[-1]
        h_last = self.dropout(h_last)
        z = self.fc(h_last)
        return z

class Decoder(nn.Module):
    def __init__(self, latent_dim, hidden_dim, output_dim, num_layers, seq_len, dropout=0.3):
        super().__init__()
        self.seq_len = seq_len
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTM(latent_dim, hidden_dim, num_layers,
                            batch_first=True, dropout=dropout if num_layers>1 else 0)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, z):
        z_expanded = z.unsqueeze(1).repeat(1, self.seq_len, 1)
        out, _ = self.lstm(z_expanded)
        out = self.dropout(out)
        logits = self.fc(out)
        return logits

class LSTM_Autoencoder(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, num_layers, seq_len):
        super().__init__()
        self.encoder = Encoder(input_dim, hidden_dim, latent_dim, num_layers)
        self.decoder = Decoder(latent_dim, hidden_dim, input_dim, num_layers, seq_len, dropout=0.3)

    def forward(self, x):
        z = self.encoder(x)
        recon_logits = self.decoder(z)
        return recon_logits, z

class FocalLoss(nn.Module):
    def __init__(self, alpha=0.95, gamma=0.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):
        bce_loss = nn.functional.binary_cross_entropy_with_logits(inputs, targets, reduction='none')
        pt = torch.exp(-bce_loss)
        focal_weight = (1 - pt) ** self.gamma
        alpha_weight = targets * self.alpha + (1 - targets) * (1 - self.alpha)
        loss = alpha_weight * focal_weight * bce_loss
        return loss.mean()

# Instantiate model, loss, optimizer
model = LSTM_Autoencoder(input_dim=NUM_PITCHES,
                         hidden_dim=HIDDEN_DIM,
                         latent_dim=LATENT_DIM,
                         num_layers=NUM_LAYERS,
                         seq_len=WINDOW_LEN).to(device)

criterion = FocalLoss(alpha=0.95, gamma=0.0)   # α=0.95 gives 0.95 weight to notes, 0.05 to silence
optimizer = optim.Adam(model.parameters(), lr=LR)

print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

# %% [markdown]
# ## 6. Training Loop (with L1 penalty on latent)

# %% [code]
train_losses = []
val_losses = []

for epoch in range(1, EPOCHS+1):
    model.train()
    epoch_train_loss = 0.0
    for batch in train_loader:
        batch = batch.to(device)
        optimizer.zero_grad()
        recon_logits, z = model(batch)
        loss = criterion(recon_logits, batch)
        l1_penalty = 0.001 * torch.norm(z, p=1)   # encourages non‑zero latent
        loss = loss + l1_penalty
        loss.backward()
        optimizer.step()
        epoch_train_loss += loss.item() * batch.size(0)
    epoch_train_loss /= len(train_dataset)

    # Validation
    model.eval()
    epoch_val_loss = 0.0
    with torch.no_grad():
        for batch in val_loader:
            batch = batch.to(device)
            recon_logits, _ = model(batch)
            loss = criterion(recon_logits, batch)
            epoch_val_loss += loss.item() * batch.size(0)
    epoch_val_loss /= len(val_dataset)

    train_losses.append(epoch_train_loss)
    val_losses.append(epoch_val_loss)

    if epoch % 5 == 0:
        print(f"Epoch {epoch:2d}/{EPOCHS} | Train Loss: {epoch_train_loss:.4f} | Val Loss: {epoch_val_loss:.4f}")

# Plot loss curves
plt.figure(figsize=(10,5))
plt.plot(range(1, EPOCHS+1), train_losses, label='Train Loss')
plt.plot(range(1, EPOCHS+1), val_losses, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Reconstruction Loss Curve (Focal α=0.95, γ=0)')
plt.legend()
plt.grid(True)
plt.savefig("plots/loss_curve.png", dpi=150)
plt.show()

# Trained model saving
torch.save(model.state_dict(), "model_task1.pt")
print("Model saved to model_task1.pt")

# %% [markdown]
# ## 7. Generate 5 MIDI Samples (with probability scaling and low threshold)

# %% [code]
def pianoroll_to_midi(pianoroll, fs=FS, threshold=GEN_THRESHOLD, velocity=80, min_duration=MIN_NOTE_DURATION):
    """Convert binary pianoroll (T, 88) to pretty_midi object."""
    midi = pretty_midi.PrettyMIDI(initial_tempo=120.0)
    piano = pretty_midi.Instrument(program=0, name='Piano')

    binary = (pianoroll >= threshold).astype(int)

    for pitch_idx in range(NUM_PITCHES):
        pitch = pitch_idx + PITCH_START
        note_on = False
        start_time = 0.0
        for t in range(binary.shape[0]):
            if binary[t, pitch_idx] == 1 and not note_on:
                note_on = True
                start_time = t / fs
            elif binary[t, pitch_idx] == 0 and note_on:
                note_on = False
                end_time = t / fs
                if end_time - start_time > min_duration:
                    note = pretty_midi.Note(velocity=velocity, pitch=pitch,
                                            start=start_time, end=end_time)
                    piano.notes.append(note)
        if note_on:
            end_time = binary.shape[0] / fs
            note = pretty_midi.Note(velocity=velocity, pitch=pitch,
                                    start=start_time, end=end_time)
            piano.notes.append(note)

    midi.instruments.append(piano)
    return midi

model.eval()
print("\nGenerating MIDI samples with probability scaling and low threshold...")
with torch.no_grad():
    for i in range(NUM_GEN_SAMPLES):
        z = torch.randn(1, LATENT_DIM).to(device)
        recon_logits = model.decoder(z)
        recon_probs = torch.sigmoid(recon_logits).cpu().numpy()[0]   # shape (T, 88)
        # Scale probabilities to boost weak note signals
        recon_probs_scaled = np.clip(recon_probs * PROB_SCALE, 0, 1)
        print(f"Sample {i+1}: original max prob = {recon_probs.max():.4f}, scaled max = {recon_probs_scaled.max():.4f}")
        midi_obj = pianoroll_to_midi(recon_probs_scaled, threshold=GEN_THRESHOLD, min_duration=MIN_NOTE_DURATION)
        out_path = f"generated_midi/generated_sample_{i+1}.mid"
        midi_obj.write(out_path)
        print(f"  Saved {out_path}")

# %% [markdown]
# ## 8. Check Generated Samples
# You can listen to the MIDI files in the `generated_midi/` folder.
# The loss curve is saved as `plots/loss_curve.png`.
#
# **If still silent:** Try reducing `GEN_THRESHOLD` to 0.01 or increasing `PROB_SCALE` to 3.0.

# %% [code]
print("Task 1 completed. Deliverables:")
print(" - Autoencoder implementation code (this notebook)")
print(" - Reconstruction loss curve: plots/loss_curve.png")
print(f" - {NUM_GEN_SAMPLES} generated MIDI samples: generated_midi/ directory")

!zip -r my_results.zip .

import os
from IPython.display import FileLink, display

# List all files you want to download
files_to_download = [
    "model_task1.pt",
    "pianoroll_train.npy",
    "pianoroll_validation.npy",
    "pianoroll_test.npy",
    "generated_midi/generated_sample_1.mid",
    "generated_midi/generated_sample_2.mid",
    "generated_midi/generated_sample_3.mid",
    "generated_midi/generated_sample_4.mid",
    "generated_midi/generated_sample_5.mid",
    "plots/loss_curve.png",
    "plots/duration_histogram.png",
    "plots/pitch_distribution.png"
]

for f in files_to_download:
    if os.path.exists(f):
        display(FileLink(f))
    else:
        print(f"Not found: {f}")